steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/vertex-grant-agent:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/vertex-grant-agent:latest'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/vertex-grant-agent:$BUILD_ID'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/vertex-grant-agent:latest'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'vertex-grant-agent'
      - '--image'
      - 'gcr.io/$PROJECT_ID/vertex-grant-agent:$BUILD_ID'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID,ENVIRONMENT=production'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--concurrency'
      - '50'
      - '--timeout'
      - '3600'
      - '--max-instances'
      - '10'

images:
  - 'gcr.io/$PROJECT_ID/vertex-grant-agent:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/vertex-grant-agent:latest'

# Redis removed for simplified deployment

options:
  logging: CLOUD_LOGGING_ONLY 